### ISSUE TITLE
Last notes pages missing

### ISSUE THREAD

**Issue by ATechWriter** [susanBuck/dwa15-fall2016-notes#11]
The notes after the lesson on Models do not appear in the 03_Laravel directory. They're only accessible from the lecture pages on dwa15.com.

**Comment by susanBuck** [comment]
I am able to see the notes after Models on my end. 

That's via this URL:
https://github.com/susanBuck/dwa15-fall2016-notes/tree/master/03_Laravel

Can you confirm/deny if you're visiting from a different URL?
<img width="1163" alt="2016-12-16_1801" src="https://cloud.githubusercontent.com/assets/237711/21281336/cf389052-c3b9-11e6-904d-83c21cc8269c.png">

**Comment by ATechWriter** [comment]
I'm not sure where the problem was, but it seems to have resolved itself.
When I visited a page from the lecture page link, the next time I went to
the repo that page would show up on the list. So by visiting from the
lecture page, I seemed to "populate" the repo page.

In any case, I can't reproduce the problem now. But thanks for looking into
it!

--Lisa

**Comment by susanBuck** [comment]
Odd! Rather have a false alarm over having content in the wrong place, so thanks for the heads up regardless! : )

Susan
