### ISSUE TITLE
Broken link for Nano cheat sheet

### ISSUE THREAD

**Issue by ATechWriter** [susanBuck/dwa15-fall2016-notes#2]
Location: 00_Command_Line/06_Nano.md, end of the "Saving" section

The link to the Nano cheat sheet (http://mintaka.sdsu.edu/reu/nano.html) returns a 404.

**Comment by susanBuck** [comment]
Substituted in other instructions:
https://github.com/susanBuck/dwa15-fall2016-notes/commit/404da4dc1064f6e99dcc3022836bd397aca79714
